api:
  image: stackstorm/st2api
  links:
    - mongo
    - rabbitmq
  volumes_from:
    - data

auth:
  image: stackstorm/st2auth
  links:
    - api
    - mongo
  volumes:
    - ./auth/htpasswd:/etc/st2/htpasswd:ro
  volumes_from:
    - data

notifier:
  image: stackstorm/st2notifier
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

resultstracker:
  image: stackstorm/st2resultstracker
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

rulesengine:
  image: stackstorm/st2rulesengine
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

sensorcontainer:
  image: stackstorm/st2sensorcontainer
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

actionrunner:
  build: ./actionrunner #[inline]
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

web:
  build: ./web
  links:
    - api
    - auth
  ports:
    - 80:80
    - 443:443

client:
  build: ./client
  links:
    - api
    - auth

## External Services
mongo:
  image: mongo

rabbitmq:
  image: rabbitmq

## Data container
data:
  build: ./data
  volumes:
    - /etc/st2
    - /opt/stackstorm/packs
  links:
    - rabbitmq
    - mongo
